# Generated by Django 4.1.2 on 2022-10-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Todo",
            new_name="Task",
        ),
    ]
