# Generated by Django 4.1.2 on 2022-10-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0002_rename_todo_task"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="time_left",
            new_name="time_due",
        ),
    ]
