# Generated by Django 4.1.2 on 2022-10-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0003_rename_time_left_task_time_due"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="is_completed",
            field=models.BooleanField(),
        ),
    ]
