# Generated by Django 4.1.2 on 2022-10-07 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0004_alter_task_is_completed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="date",
        ),
    ]
